import os

guides = {
    "how-to-build-a-10k-month-app-in-2026.md": """### Name
How to Build a $10k/Month App in 2026

### Description
A 60-second blueprint on building and launching a profitable app, from idea generation to deployment and marketing.

### Content

#### 1. Idea Generation
- Stop obsessing over a completely unique idea.
- Use **Sensor Tower** or **Trust MRR** to find apps already generating real revenue.
- Find ways to tweak or improve them to create your own version.

#### 2. Choose Your Stack
- **Web App**: Use **Next.js** for seamless front-end and back-end development.
- **Mobile App**: Use **React Native** and **Expo Go** to build for both Apple and Android simultaneously.

#### 3. Leverage AI Tools
- Familiarize yourself with AI coding assistants.
- **Claude Coder**: Best for front-end design and user experience.
- **Codex**: Best for complex backend architecture.

#### 4. Backend & Payments
- **Database / Backend**: Supabase or Firebase.
- **Payments**: Stripe (Web) or RevenueCat (Mobile).

#### 5. Launch & Distribute
- Release early to get user feedback immediately.
- **Deployment**: Vercel (free for web), App Store ($99/yr), Play Store ($25/yr).
- **Marketing**: Grow organically through TikTok, Instagram, UGC, Reddit, or Product Hunt.
- **Scale**: Once organic works, turn the winning formulas into paid ads.

### Category
Guides

### Tags
- App Development
- Business
- Software
""",
    "how-to-find-a-tech-job-in-2026.md": """### Name
How to Find a Tech Job in 2026

### Description
A concise blueprint for breaking into tech and landing a software engineering job in a competitive market.

### Content

#### 1. Master LeetCode
- Start practicing daily well before the recruiting cycle begins.
- If you don't know where to start, focus on the **Blind 75** list on LeetCode.

#### 2. Learn a High-Demand Skill
- If your resume isn't getting bites, you need new skills.
- Dive deep into **AWS** (via AWS Skill Builder) or **Spring Boot**.
- Recommended resource: *Amigoscode* on YouTube.

#### 3. Build Something Valuable
- Classes and degrees are no longer enough.
- Build a significant project that takes at least 3-6 weeks to complete to showcase on your resume.

#### 4. Network Relentlessly
- "It's not what you know, it's who you know."
- Attend career fairs and hackathons.
- Message your connections directly when applying for jobs; referrals are the easiest way to get an interview.

### Category
Guides

### Tags
- Career
- Software Engineering
- Job Search
""",
    "5-ai-businesses-to-make-1m.md": """### Name
5 AI Businesses to Make $1M (With Zero Employees)

### Description
A breakdown of 5 high-leverage AI service businesses you can start today, including a 4-step framework for launching.

### Content

#### The AI Startup Ladder (4-Step Process)
1. **Validate**: Pick a niche (e.g., med spas, agencies) and do outreach to prove demand.
2. **Pre-sell**: Sell the service and collect cash before building. Use a simple document with a Stripe checkout link.
3. **Deliver**: Once paid, drop everything to manually deliver the result within 48 hours. This builds your reputation and earns referrals.
4. **Build & Automate**: Productize the service to scale deployment.

#### 1. AI Inbox & Calendar Manager (Highest Potential)
- **What it is**: Building an AI executive assistant to manage emails and meetings for busy CEOs.
- **Why it works**: Entrepreneurs desperately want to buy back their time.
- **Income Potential**: $3,000 - $5,000 / day.

#### 2. AI Data Cleanup Agency
- **What it is**: Organizing a company's messy internal data (emails, CRMs, spreadsheets), vectorizing it, and putting an AI search layer on top.
- **Why it works**: Businesses need to make better decisions based on their own data.
- **Income Potential**: $1,500 - $3,000 / day.

#### 3. AI Sales Chatbot
- **What it is**: Creating a chatbot that converts social media chats, texts, and emails into leads and sales.
- **Why it works**: Business owners get massive inbound engagement but lack time to reply.
- **Income Potential**: $1,000 - $1,500 / day.

#### 4. AI Content Repurposing Service
- **What it is**: Turning long-form content (podcasts, webinars) into short-form clips for TikTok/Reels using AI tools.
- **Why it works**: Algorithms favor niche short-form content.
- **Income Potential**: $750 - $1,000 / day.

#### 5. AI Appointment Setter
- **What it is**: Replacing human inbound phone agents with AI voice agents to book sales calls.
- **Why it works**: Cheaper than a human, available 24/7, and performs incredibly well.
- **Income Potential**: $500 - $1,000 / day.

### Category
Guides

### Tags
- Business
- AI Agents
- Entrepreneurship
""",
    "build-5k-month-ai-websites.md": """### Name
How to Sell $5,000/Month AI Websites

### Description
A complete workflow for building high-ticket, automated AI websites for local businesses using GoHighLevel and AI tools.

### Content

Stop selling basic $300 websites generated by ChatGPT. To charge high-ticket retainers ($3k-$5k/month), you must sell **systems**, not just sites. This means integrating CRMs, automated follow-ups, and AI booking tools.

#### Step 1: Scrape Competitor Formats
- Go to the **Facebook Ad Library** and find competitors in your niche (e.g., bathroom remodeling) that are running ads.
- If they are running ads, their website converts.
- Copy their URL and use **Firecrawl** to scrape the site for its `markdown` (structure) and `branding` (colors).

#### Step 2: Generate the Foundation
- Find your target client's existing (outdated) website and scrape their logo/branding.
- Paste the competitor's markdown + your client's branding into **Claude AI** or the **GoHighLevel AI Studio**.
- Prompt: *"Make me a website similar to this structure, optimized for cold traffic conversions, using this new branding."*

#### Step 3: Create Authentic UGC Images with AI
- Don't use obvious AI-generated images or stock photos.
- Go to **Pinterest**, search for organic UGC (User Generated Content) style photos in the niche.
- Use tools like **Hixfield**, **Nano Banana Pro**, or **Midjourney** as an image-to-image generator.
- Prompt: *"Generate an image of a modern bathroom, UGC iPhone style picture, using the layout of the reference photo."*
- You can even generate perfect "Before & After" split-screen photos using AI.

#### Step 4: Add Backend Automation (The $5k Value)
- Build the site inside **GoHighLevel** so it natively connects to a CRM.
- **Automated Follow-ups**: When a lead fills a form, immediately trigger an SMS ("Hey, got your request, calling in 5 mins!").
- **Reactivation Campaigns**: If a lead goes cold, automate an email/SMS 60 days later to revive them.
- **Booking & Payments**: Allow customers to book calendar slots and pay directly on the site.

#### Step 5: Sales
- Cold call, DM, or SMS local businesses.
- Send them a preview link of the completed AI website (built in 10 minutes) before they even pay. 
- Upsell them on the backend automation and ad-management.

### Category
Guides

### Tags
- Web Design
- GoHighLevel
- Agency
- Sales
"""
}

os.makedirs('organized-data/Guides', exist_ok=True)

for filename, content in guides.items():
    filepath = os.path.join('organized-data/Guides', filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

print("Created 4 guides.")
